env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:import/typescript"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  'react/jsx-filename-extension': [2, { 'extensions': ['.jsx', '.js', '.tsx']}],
  "no-use-before-define": "off",
  "@typescript-eslint/no-use-before-define": [ "error" ],
  "no-shadow": "off",
  "@typescript-eslint/no-shadow": [ "error" ],
  "no-unused-vars": "off",
  "@typescript-eslint/no-unused-vars": "error",
  "max-len": [ "error", { code: 140 } ],
  "react/prop-types": "off",
  "no-underscore-dangle": "off",
  "import/extensions": [
    "error",
    {
      "js": "never",
      "jsx": "never",
      "ts": "never",
      "tsx": "never"
    }
  ]
}
